### ISSUE TITLE
Design a better looking UI for the Add-On

### ISSUE THREAD

**Issue by horner** [mieweb/wikiGDrive#254]
See Screenshot.
![image](https://user-images.githubusercontent.com/6094599/167262962-cc1290ef-cb52-4984-9069-bf178a34c0cc.png)

Here is a link to play:
https://google-drive-iframe.wikigdrive.com/drive/0APmwe3yIhGabUk9PVA/folder/0APmwe3yIhGabUk9PVA/1O9wKbDsMhFCUG207rHq_PvdmflsuYQMzcWbnuq4Sq_U

Example URL (enable the Add-on) and view sidebar. 
https://docs.google.com/document/d/1O9wKbDsMhFCUG207rHq_PvdmflsuYQMzcWbnuq4Sq_U/edit?usp=sharing

**Comment by horner** [comment]
@wreiske it would be good to have you and Austin discuss this and come up with a better looking UI that is user focused.

I love the preview, but I am sure the typical user would prefer to see the links to common actions which I think will be:

1) Sync
2) Preview (go to the HTML version)
3) What links here
4) Navigation
5) git commit  (maybe this is higher up actually)

then then the rest

**Comment by horner** [comment]
This is the source code for the vue: https://github.com/mieweb/wikiGDrive/tree/master/src/containers/server/static/assets/components

**Comment by wreiske** [comment]
@austinKesler, let's add this to our daily to review next week.

**Comment by wreiske** [comment]
On the calendar to review Thursday, May 19th.

**Comment by wreiske** [comment]
From a first look, it might be good to come up with a better sidebar size and then build a mockup for the sidebar design based on that new size. 350px may be a little too small for everything that would want to be portrayed on the sidebar. 
https://github.com/mieweb/wikiGDrive/blob/f06b38014ba8548fd1f5cf49ba175f75031f0dab/app_script/Code.gs#L68-L71

https://developers.google.com/apps-script/guides/dialogs#custom_sidebars

We may also want to simplify the sidebar and only include the most important tasks rather than everything available on the first sidebar view. If someone wants to do more advanced tasks, there are other methods like dialogs or even opening a new browser tab to complete those tasks. For example git commits could be done with a prompt dialog (https://developers.google.com/apps-script/guides/dialogs#prompt_dialogs).

Met with Doug for a bit and Austin and I met for longer to discuss the next steps. Austin is going to look at what is there and think up a design for the sidebar incorporating what we think is most important. (preview, git commits, toc, backlinks, etc.).

The side by side "preview" will eventually be a Hugo rendered HTML output of just the document, an example of what that might look like is here:
![image](https://user-images.githubusercontent.com/6295044/169385424-b91f12b3-3638-4dbc-9c2f-3516ea33ffa4.png)

We have a weekly standing meeting to keep progress rolling.

**Comment by ggodlewski** [comment]
> Note: Add-on sidebars have a fixed width of 300 pixels that you can't alter by calling [HtmlOutput.setWidth(width)](https://developers.google.com/apps-script/reference/html/html-output#setwidthwidth).

https://developers.google.com/apps-script/add-ons/concepts/dialogs

**Comment by wreiske** [comment]
New mockup to discuss on Thursday.

https://xd.adobe.com/view/a31d1cdc-fa90-4f1e-b71e-c820f2984b2c-f64e/

![image](https://user-images.githubusercontent.com/6295044/169902307-b76da0a3-1252-459c-93fc-1c83be997010.png)
![image](https://user-images.githubusercontent.com/6295044/169902361-70ed08ff-cad8-4776-b2b8-a8514a433a4f.png)

You can see the rest of the pages using the XD link above.

**Comment by horner** [comment]
@wreiske I asked Austin to make the HTML for this via Rocket just now.

**Comment by AwesomeKesler** [comment]
Working on this-
![wiki-g-drive](https://user-images.githubusercontent.com/97115745/176703450-b1b99098-9e4c-4197-a4f6-f2a4eaa5d9b2.gif)
-

**Comment by AwesomeKesler** [comment]
[wgd_static_page.zip](https://github.com/mieweb/wikiGDrive/files/9074104/wgd_static_page.zip)
static html for the addon layout. Will and I have discussed some next steps for this.

**Comment by horner** [comment]
#369 
 is now the source of truth
