### ISSUE TITLE
Screenshots not showing in updated help document that was sync'd

### ISSUE THREAD

**Issue by anichols27** [mieweb/wikiGDrive#382]
Hi! Bridget and I worked on publishing an updated help document named Merge Manager Tab.
Everything updated and is out there to be visible EXCEPT the new screenshots added into the document.
The screenshots do show on the extension/wikig-drive version that we sync'd and viewed.  But the public facing docs.enterprisehealth.com doesn't show it.  Here are some screenshots.  Please let us know how to fix so that when we update help documents, that screenshots also get included.
![8-10a](https://github.com/mieweb/docs/assets/137406473/a68b3538-e051-451e-bb19-ae9096febc63)
![8-10b](https://github.com/mieweb/docs/assets/137406473/c6218657-86d5-4561-ab17-1f2ec8b4d5c3)

**Comment by ggodlewski** [comment]
@horner 

The images seems to be in the gh repo. Did you do it https://github.com/mieweb/docs/commit/09d3f27bb50bb960bb8f54a61669e840f8fca52e from UI or CLI?

The image seems still to be missing https://docs.enterprisehealth.com/functions/system-administration/system-controls/merge-manager-tab/
The build failed https://github.com/mieweb/docs/runs/16018148303 I don't have access to the logs. Probably not related to wikigdrive because the preview looks ok.

**Comment by ggodlewski** [comment]
After lase build https://docs.enterprisehealth.com/functions/system-administration/system-controls/merge-manager-tab/ looks ok. Can we close it?

**Comment by horner** [comment]
I had to manually commit the image from the CLI.
  If you make a document and add an image the image wont be committed in the diff.

**Comment by monpie3** [comment]
Since it is in the Done status, I'm closing the ticket.
