### ISSUE TITLE
Fix anchor links

### ISSUE THREAD

**Issue by ggodlewski** [mieweb/wikiGDrive#472]
In Sending HL7 Messages to System the anchor links do not work:

https://wikigdrive.com/drive/0AF_nrE0_QH_2Uk9PVA/content/functions/system-administration/interfaces/sending-hl7-messages-to-system.md

**Comment by horner** [comment]
@hammbi @auhrick

**Comment by monpie3** [comment]
I've tested this directly on: https://docs.enterprisehealth.com/functions/system-administration/interfaces/sending-hl7-messages-to-system/
and these links are not links to specific sections still.
Clicking on a link does not redirect to a specific place on a given page. 
Not necessarily something needs to be implemented, maybe it’s enough just to edit the file itself.

![Image](https://github.com/user-attachments/assets/d579b6ff-6d57-4a29-9536-84f77e0d6a39)

**Comment by ggodlewski** [comment]
It is fixed on https://dev.wikigdrive.com/drive/0AF_nrE0_QH_2Uk9PVA/content/functions/system-administration/interfaces/sending-hl7-messages-to-system.md#html

![Image](https://github.com/user-attachments/assets/e93d4c7c-c339-4ba7-b8e9-deeda6232fcf)

We're waiting for new deployment.

**Comment by monpie3** [comment]
got it! I just tested it on dev system: 
https://dev.wikigdrive.com/preview/0AF_nrE0_QH_2Uk9PVA/_manual/functions/system-administration/interfaces/sending-hl7-messages-to-system/?388#message-header-msh

and it looks like out href attribute value is loo short right now, it only contains fragment identifier: 

![image](https://github.com/user-attachments/assets/363b106d-e838-46f4-8a72-bc20aa54fcd1)

and due to this we are not being redirected to the correct page
